# Generated by Django 4.2 on 2023-04-07 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=256, null=True)),
                ("citable_reference", models.CharField(max_length=256, null=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
    ]
